var arrlang = {
    'ko' : {
        'join' : '지금 가입하기',
        'login' :  '로그인',
        'title' : '캡틴마블',
        'time'  : '2019  |  12+  |  123분  |  액션, 모험, SF',
        'main' : "1990년대를 배경으로 한 마블 스튜디오 '캡틴 마블'은 이전에 볼 수 없었던 마블 시네마틱 유니버스 역사상 전혀 새로운 모험으로, 캐럴 댄버스가 우주의 가장 강력한 영웅 중 한 명이 되는 그녀의 여정을 따라간다. 두 외계 종족 간의 은하 전쟁이 지구에 다가오는 동안 댄버스는 자신과 동료 협력자가 혼란의 소용돌이 중심에 있음을 알게 되는데...",
        'actor' : '주연: 브리 라슨, 사무엘 L. 잭슨',
        'now' : '지금 시청하기',
        'line1' : '한계를 뛰어 넘는 슈퍼 히어로의 탄생',
        'line2' : "2019 28회 MTV영화제(최고의 싸움상) '캡틴 마블'",
        'vid' : '영상',
        'continue' : '예고편',
        'character' : '캐릭터',
        'ch1' : '캡틴마블',
        'ch2' : '닉 퓨리',
        'ch3' : '욘-로그',
        'ch4' : '마리아 램보',
        'ch5' : '탈로스',
        'detail' : '상세정보',
        'detailtitle1' : '오프라인 시청',
        'detailcontent1' : '저장 가능 콘텐츠',
        'detailtitle2' : '장르',
        'detailcontent2' : '영화/SF, 액션 & 어드벤처',
        'detailtitle3' : '영화 특징:',
        'detailcontent3' : '흥미진진',
        'detailtitle4' : '음성/더빙',
        'detailcontent4' : 'English, Korean - Audio Description, Korean [Original]',
        'detailtitle5' : '자막',
        'detailcontent5' : 'English, Korean',
        'detailtitle6' : '출연',
        'detailcontent6' : '브리 라슨, 사무엘 L. 잭슨',
        'detailcontent7' : '벤 멜델슨',
        'detailcontent8' : '주드 로',
        'detailcontent9' : '라샤나 린치',
        'detailcontent10' : '아네트 베닝',
        'similar' : '비슷한 콘텐츠',
        'notice' : '공개임박',
        'noticetitle1' : '샹치와 텐링즈의 전설',
        'noticecontent1' : "초인적인 능력을 가진 ‘텐 링즈’의 힘으로 수세기 동안 어둠의 세상을 지배해 온 ‘웬우’ '샹치’는 아버지 ‘웬우’ 밑에서 암살자로 훈련을 받았지만 이를 거부하고 평범함 삶을 선택한다.",
        'noticetitle2' : '이터널스',
        'noticecontent2' : "마블 스튜디오의 <이터널스>는 수 천년에 걸쳐 그 모습을 드러내지 않고 살아온 불멸의 히어로들이 <어벤져스: 엔드게임> 이후 인류의 가장 오래된 적 '데비안츠'에 맞서기 위해 다시 힘을 합치면서 벌어지는 이야기",
        'call' : '질문이 있으신가요? 문의전화: 123-456-7890',
        'inform1' : '자주 묻는 질문',
        'inform2' : '투자 정보(IR)',
        'inform3' : '개인 정보',
        'inform4' : '속도 테스트',
        'inform5' : '고객 센터',
        'inform6' : '입사 정보',
        'inform7' : '쿠키 설정',
        'inform8' : '법적 고지',
        'inform9' : '계정',
        'inform10' : '미디어 센터',
        'inform11' : '이용약관',
        'inform12' : '문의하기',
        'follow' : 'FOLLOW MARVEL',
        'copy' : '마블 대한민국 ©2021 MARVEL'
    },

    'en' : {
        'join' : 'Join Now',
        'login' : 'Login',
        'title' : 'Captain Mavel',
        'time'  : '2019 | 12+ | 123 min | Action, Adventure, SF',
        'main' : "Set in the 1990s, Marvel Studios 'Captain Marvel' is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe that follows the journey of Carol Danvers as she becomes one of the universe's most powerful heroes. While a galactic war between two alien races reaches Earth, Danvers finds herself and a small cadre of allies at the center of the maelstrom.",
        'actor' : 'Starring: Brie Larson, Samuel L. Jackson',
        'now' : 'WHATCH NOW',
        'line1' : 'The birth of a superhero who pushes herself past the limits',
        'line2' : "28th MTV Award 2019(Best Fight) 'Captain Marvel'",
        'vid' : 'VIDEOS',
        'continue' : 'TRAILERS',
        'character' : 'CHARACTERS',
        'ch1' : 'CAPTAIN MARVEL',
        'ch2' : 'NICK FURY',
        'ch3' : 'YON-ROGG',
        'ch4' : 'MARIA RAMBEAU',
        'ch5' : 'TALOS',
        'detail' : 'More Details',
        'detailtitle1' : 'Watch offline',
        'detailcontent1' : 'Available to download',
        'detailtitle2' : 'Genres',
        'detailcontent2' : 'Sci-Fi Movies, Action & Adventure',
        'detailtitle3' : 'This movie is...',
        'detailcontent3' : 'Exciting',
        'detailtitle4' : 'Audio',
        'detailcontent4' : 'English, Korean - Audio Description, Korean [Original]',
        'detailtitle5' : 'Subtitles',
        'detailcontent5' : 'English, Korean',
        'detailtitle6' : 'Cast',
        'detailcontent6' : 'Brie Larson, Samuel L. Jackson',
        'detailcontent7' : 'Ben Mendelsohn',
        'detailcontent8' : 'Jude Law',
        'detailcontent9' : 'Lashana Lynch',
        'detailcontent10' : 'Annette Bening',
        'similar' : 'More Like This',
        'notice' : 'Coming Soon',
        'noticetitle1' : 'Shang-Chi and the Legend of the Ten Rings',
        'noticecontent1' : "Marvel Studios' 'Shang-Chi and The Legend of The Ten Rings' stars Simu Liu as Shang-Chi, who must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
        'noticetitle2' : 'Eternals',
        'noticecontent2' : "Marvel Studios' Eternals features an exciting new team of Super Heroes in the Marvel Cinematic Universe, ancient aliens who have been living on Earth in secret for thousands of years. Following the events of Avengers: Endgame, an unexpected tragedy forces them out of the shadows to reunite against mankind's most ancient enemy, the Deviants.",
        'call' : 'Questions? Call 123-456-7890',
        'inform1' : 'FAQ',
        'inform2' : 'Investor Relations',
        'inform3' : 'Privacy',
        'inform4' : 'Speed Test',
        'inform5' : 'Help Center',
        'inform6' : 'Jobs',
        'inform7' : 'Cookie Preferences',
        'inform8' : 'Legal Notices',
        'inform9' : 'Account',
        'inform10' : 'Media Center',
        'inform11' : 'Terms of Use',
        'inform12' : 'Contact Us',
        'follow' : 'FOLLOW MARVEL',
        'copy' : '©2021 MARVEL KOREA'
    }
};

$('header #lang').change(function(){
    var lang = $(this).val();
    var langue = $('.lang');
    var arr = arrlang[lang];

    langue.each(function(index, element){
        for(var i = 0;i<langue.length;i++){
        if(index==i){
        $(this).text(arr[$(this).attr('key')]);
        }
    }
    });
});