var arrlang = {
    'ko' : {
        'join' : '지금 가입하기',
        'login' :  '로그인',
        'join2' : '지금 가입하기',
        'login2' :  '로그인',
        'news' : '뉴스',
        'comics' :  '코믹스',
        'character' : '캐릭터',
        'movie' :  '영화',
        'broadcast' : '방송',
        'game' :  '게임',
        'video' : '비디오',
        'more' :  '더보기',
        'title' : '가디언즈 오브 갤럭시 3',
        'time'  : '2023  |  15+  |  150분  |  액션, 모험, SF',
        'main' : "‘가모라’를 잃고 슬픔에 빠져 있던 ‘피터 퀼’이 위기에 처한 은하계와 동료를 지키기 위해 다시 한번 가디언즈 팀과 힘을 모으고, 성공하지 못할 경우 그들의 마지막이 될지도 모르는 미션에 나서는 이야기",
        'actor' : '크리스 프렛, 조 샐다나, 데이브 바티스타, 빈 디젤',
        'now' : '지금 시청하기',
        'line1' : '가디언즈 오브 갤럭시의 마지막이 될지도 모르는 이야기',
        'vid' : '영상',
        'continue' : '예고편',
        'character' : '캐릭터',
        'ch1' : '스타로드',
        'ch2' : '로켓',
        'ch3' : '그루트',
        'ch4' : '드렉스',
        'ch5' : '맨티스',
        'ch6' : '네뷸라',
        'detail' : '상세정보',
        'detailtitle1' : '오프라인 시청',
        'detailcontent1' : '저장 가능 콘텐츠',
        'detailtitle2' : '장르',
        'detailcontent2' : '영화/SF, 액션 & 어드벤처',
        'detailtitle3' : '영화 특징:',
        'detailcontent3' : '흥미진진',
        'detailtitle4' : '음성/더빙',
        'detailcontent4' : 'English, Korean - Audio Description, Korean [Original]',
        'detailtitle5' : '자막',
        'detailcontent5' : 'English, Korean',
        'detailtitle6' : '출연',
        'detailcontent6' : '크리스 프렛',
        'detailcontent7' : '조 샐다나',
        'detailcontent8' : '데이브 바티스타',
        'detailcontent9' : '빈 디젤',
        'detailcontent10' : '브래들리 쿠퍼',
        'similar' : '비슷한 콘텐츠',
        'notice' : '공개임박',
        'noticetitle1' : '더 마블스',
        'noticecontent1' : "더 높이! 더 멀리! 더 빨리! 역대급 파장을 일으킬 마블의 NEW 팀업이 시작된다!",
        'noticetitle2' : '캡틴 아메리카: 브레이브 뉴 월드',
        'noticecontent2' : "마블 시네마틱 유니버스 페이즈 5의 다섯 번째 영화이자 캡틴 아메리카 실사영화 시리즈의 네 번째 작품",
        'call' : '질문이 있으신가요? 문의전화: 123-456-7890',
        'inform1' : '자주 묻는 질문',
        'inform2' : '투자 정보(IR)',
        'inform3' : '개인 정보',
        'inform4' : '속도 테스트',
        'inform5' : '고객 센터',
        'inform6' : '입사 정보',
        'inform7' : '쿠키 설정',
        'inform8' : '법적 고지',
        'inform9' : '계정',
        'inform10' : '미디어 센터',
        'inform11' : '이용약관',
        'inform12' : '문의하기',
        'follow' : 'FOLLOW MARVEL',
        'copy' : '마블 대한민국 ©MARVEL KOREA'
    },

    'en' : {
        'join' : 'Join Now',
        'login' : 'Login',
        'join2' : 'Join Now',
        'login2' : 'Login',
        'news' : 'news',
        'comics' :  'comics',
        'character' : 'characters',
        'movie' :  'movie',
        'broadcast' : 'broadcast',
        'game' :  'gmae',
        'video' : 'video',
        'more' :  'more',
        'title' : 'Guardians of the Galaxy 3',
        'time'  : '2023 | 15+ | 150 min | Action, Adventure, SF',
        'main' : "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
        'actor' : 'Starring: Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
        'now' : 'WHATCH NOW',
        'line1' : 'The story that could mean the end of the Guardians',
        'vid' : 'VIDEOS',
        'continue' : 'TRAILERS',
        'character' : 'CHARACTERS',
        'ch1' : 'Star Lord',
        'ch2' : 'Roket',
        'ch3' : 'Groot',
        'ch4' : 'Drax',
        'ch5' : 'Mantis',
        'ch6' : 'Nebula',
        'detail' : 'More Details',
        'detailtitle1' : 'Watch offline',
        'detailcontent1' : 'Available to download',
        'detailtitle2' : 'Genres',
        'detailcontent2' : 'Sci-Fi Movies, Action & Adventure',
        'detailtitle3' : 'This movie is...',
        'detailcontent3' : 'Exciting',
        'detailtitle4' : 'Audio',
        'detailcontent4' : 'English, Korean - Audio Description, Korean [Original]',
        'detailtitle5' : 'Subtitles',
        'detailcontent5' : 'English, Korean',
        'detailtitle6' : 'Cast',
        'detailcontent6' : 'Chris Pratt',
        'detailcontent7' : 'Zoe Saldana',
        'detailcontent8' : 'Dave Bautista',
        'detailcontent9' : 'Vin Diesel',
        'detailcontent10' : 'Bradley Cooper',
        'similar' : 'More Like This',
        'notice' : 'Coming Soon',
        'noticetitle1' : 'The Marvels',
        'noticecontent1' : "Higher! Further! Faster! A Marvel NEW Team-Up Begins to Make Big Waves.",
        'noticetitle2' : 'Captain America: Brave New World',
        'noticecontent2' : "The fifth film of Marvel Cinematic Universe Phase 5 and the fourth work in the Captain America live-action film series.",
        'call' : 'Questions? Call 123-456-7890',
        'inform1' : 'FAQ',
        'inform2' : 'Investor Relations',
        'inform3' : 'Privacy',
        'inform4' : 'Speed Test',
        'inform5' : 'Help Center',
        'inform6' : 'Jobs',
        'inform7' : 'Cookie Preferences',
        'inform8' : 'Legal Notices',
        'inform9' : 'Account',
        'inform10' : 'Media Center',
        'inform11' : 'Terms of Use',
        'inform12' : 'Contact Us',
        'follow' : 'FOLLOW MARVEL',
        'copy' : '©MARVEL KOREA'
    }
};

$('header #lang').change(function(){
    var lang = $(this).val();
    var langue = $('.lang');
    var arr = arrlang[lang];

    langue.each(function(index, element){
        for(var i = 0;i<langue.length;i++){
        if(index==i){
        $(this).text(arr[$(this).attr('key')]);
        }
    }
    });
});
  // 메뉴

  $("#nav .hamb").click(function(){
    if($("#nav-lower").hasClass('on')){
        $("#nav-lower").removeClass('on');
    } else{
        $("#nav-lower").addClass('on');
    }
});
